version: '3'
services:
  php-app1:
    image: php:8.1-apache
    container_name: php-app1
    volumes:
      - ./php-app1:/var/www/html
      - /home/admin1/Vagrant-and-Docker-Files/docker-compose-two-php-apps-with-nginx-Revproxy/apache2-app1.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8081:80" # Mapping port 8081 on the host to port 80 in the container
    networks:
      - app-network

  php-app2:
    image: php:8.1-apache
    container_name: php-app2
    volumes:
      - ./php-app2:/var/www/html
      - /home/admin1/Vagrant-and-Docker-Files/docker-compose-two-php-apps-with-nginx-Revproxy/apache2-app2.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8082:80" # Mapping port 8082 on the host to port 80 in the container
    networks:
      - app-network

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - /home/admin1/Vagrant-and-Docker-Files/docker-compose-two-php-apps-with-nginx-Revproxy/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - php-app1
      - php-app2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
